
otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:5050
      compression: gzip
      insecure: true
      instance: ${random.shortuuid}
    experimental:
      expoter:
        otlp:
          retry:
            enabled: true
  metrics:
    exporter: none

datasources:
  default:
    schema-generate: CREATE_DROP
    url: 'jdbc:otel:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password: ''
    driver-class-name: io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver


jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

micronaut:
  application:
    name: example
